# Generated by Django 5.2.11 on 2026-03-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('TECHNICIAN', 'Technician'), ('CUSTOMER', 'Cliente')], default='CUSTOMER', max_length=20),
        ),
    ]
