# Generated by Django 5.2.11 on 2026-03-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sentiment',
            field=models.CharField(choices=[('ANGRY', 'Irritado'), ('NEUTRAL', 'Neutro'), ('POSITIVE', 'Satisfeito')], default='NEUTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
