# Generated by Django 5.2.11 on 2026-03-01 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_sentiment_ticket_sla_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('PDF_MANUAL', 'Manual PDF'), ('TICKET_HISTORY', 'Histórico de Ticket'), ('FAQ', 'FAQ Manual')], max_length=30)),
                ('source_name', models.CharField(help_text='Nome do arquivo PDF ou título do ticket de origem', max_length=255)),
                ('keywords', models.TextField(help_text='Palavras-chave separadas por vírgula para busca rápida')),
                ('question_hint', models.TextField(help_text='Termos/perguntas que este chunk responde')),
                ('content', models.TextField(help_text='Resposta/conteúdo completo')),
                ('confidence_score', models.FloatField(default=1.0, help_text='0.0-1.0, confiança da resposta')),
                ('page_reference', models.CharField(blank=True, help_text='Página do manual de referência', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('GREETING', 'Saudação inicial'), ('ANALYZING', 'Analisando o problema'), ('ASKING', 'Aguardando resposta do cliente'), ('SUGGESTING', 'Sugestão aguardando aprovação do técnico'), ('CONFIRMED', 'Resposta confirmada pelo técnico'), ('NO_KNOWLEDGE', 'Sem conhecimento — escalado'), ('RESOLVED', 'Resolvido')], default='GREETING', max_length=20)),
                ('pending_question', models.TextField(blank=True, help_text='Pergunta pendente feita pela IA')),
                ('clarification_count', models.IntegerField(default=0, help_text='Quantas perguntas de clarificação já foram feitas')),
                ('matched_chunk_id', models.UUIDField(blank=True, help_text='ID do KnowledgeChunk que melhor casou', null=True)),
                ('confidence', models.FloatField(default=0.0, help_text='Confiança da última busca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_state', to='tickets.ticket')),
            ],
        ),
    ]
