# Generated by Django 5.2.11 on 2026-03-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_knowledge_chunk_ai_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('PENDING_TECH', 'Aguardando Validação'), ('WAITING_USER', 'Aguardando Confirmação'), ('PROGRESS', 'Em Andamento'), ('HOLD', 'Em Espera'), ('REOPENED', 'Reaberto'), ('RESOLVED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=20),
        ),
    ]
