# Generated by Django 5.0.14 on 2026-03-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_assisted',
            field=models.BooleanField(default=False, help_text='True se teve ajuda da IA'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_knowledge_gap',
            field=models.BooleanField(default=False, help_text='True se a IA não soube responder'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_performance_score',
            field=models.IntegerField(default=0, help_text='-1: Rejeitado, 0: Neutro, 1: Validado'),
        ),
    ]
