# Generated by Django 5.0.14 on 2026-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_ai_assisted_ticket_ai_knowledge_gap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/'),
        ),
    ]
