# Generated by Django 5.0.14 on 2026-03-01 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('tickets', '0008_ticketmessage_file_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationstate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.organization'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.organization'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.organization'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.organization'),
        ),
    ]
